for real this time

diff --git a/.github/workflows/export-html5.yaml b/.github/workflows/export-html5.yaml
--- a/.github/workflows/export-html5.yaml
+++ b/.github/workflows/export-html5.yaml
@@ -44,24 +44,23 @@ jobs:
           mkdir --parents /home/runner/.local/share/godot/templates
           mv ./Godot_v3.5.1-stable_mono_export_templates/templates /home/runner/.local/share/godot/templates/3.5.1.stable.mono
 
-      # The export command can fail but still exit with status code 0... so redirect stderr to a file
-      # and fail the build if that file is not empty
+      # The export command can fail but still exit with status code 0.
+      # Specifically, in the case of a C# compile error the exit code will be 0 but stderr will have a message.
+      # So here we redirect stderr and verify that it is empty.
       - name: Export project to HTML5
         run: |
           cd ./godot
           mkdir --parents ./.export/HTML5
           godot ./project.godot --export "HTML5" 2> ./errlog.txt
-          echo "WTF c'mon now!" && cat ./errlog.txt
-          [ -s ./errlog.txt ] || (echo "stderr was not empty, failing" && cat ./errlog.txt && exit 123)
           ls -lh
           cd .export/HTML5
           ls -lh
 
-      - name: TEST
+      - name: Verify stderr was empty
         run: |
           cd ./godot
           cat ./errlog.txt
-          ([ -s ./errlog.txt ] && echo looks good) || exit 55
+          ([ -s ./errlog.txt ] && exit 55) || echo looks good
 
       - uses: actions/upload-artifact@v3
         with:
